AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance for Amsa Frontend and Backend

Resources:
  AmsaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, Backend API
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3001
          ToPort: 3001
          CidrIp: 0.0.0.0/0

  AmsaEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      KeyName: ubuntu-key.pem   # Replace with your EC2 keypair
      ImageId: ami-0a716d3f3b16d290c  # Ubuntu 22.04 AMI
      SecurityGroupIds:
        - !Ref AmsaSecurityGroup
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y
          sudo apt install -y git nginx curl
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g pm2
          sudo systemctl enable nginx
